# Generated by Django 3.2.4 on 2021-06-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socweb', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
